obj-$(CONFIG_NOTHING_BOOTLOADER_LOG)    += nothing_bootloader_log.o
obj-$(CONFIG_NOTHING_WRITRBACK_KMSG)    += nothing_writeback_kmsg.o
obj-$(CONFIG_NOTHING_DISK_USAGE)        += nothing_disk_usage.o
obj-$(CONFIG_NOTHING_DISK_USAGE)        += nothing_readahead_trace.o
obj-$(CONFIG_NOTHING_RESTART_HANDLER)   += nothing_restart_handler.o
obj-$(CONFIG_NOTHING_TASK_MEMINFO)      += nothing_task_meminfo.o
obj-$(CONFIG_NOTHING_SECURE_ELEMENT)    += nothing_secure_element.o
